spring:
  datasource:
    url: jdbc:postgresql://postgres-service:5432/bookvexedb_j2e
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  kafka:
    producer:
      bootstrap-servers: kafka-service:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

server:
  port: 8084

vnpay:
  tmnCode: VWJ2IOSO
  hashSecret: AMFRNXTX77SU7EBXP68PFQMLEQ204X2P
  payUrl: https://sandbox.vnpayment.vn/paymentv2/vpcpay.html
  returnUrl: https://unsuccinctly-unadhering-zenaida.ngrok-free.dev/api/vnpay-return/
  ipnUrl: https://unsuccinctly-unadhering-zenaida.ngrok-free.dev/api/vnpay-ipn/
  frontendReturnUrl: http://localhost:5173/payment/vnpay-return
